// /* eslint-disable */
// // @ts-nocheck
// // Generated by unplugin-vue-components
// // Read more: https://github.com/vuejs/core/pull/3399
// // biome-ignore lint: disable
// export {};
//
// /* prettier-ignore */
// declare module 'vue' {
//   export interface GlobalComponents {
//     Checkbox: typeof import('primevue/checkbox')['default']
//     DatePicker: typeof import('primevue/datepicker')['default']
//     Fieldset: typeof import('primevue/fieldset')['default']
//     FileUpload: typeof import('primevue/fileupload')['default']
//     FormField: typeof import('@primevue/forms/formfield')['default']
//     InputText: typeof import('primevue/inputtext')['default']
//     RouterLink: typeof import('vue-router')['RouterLink']
//     RouterView: typeof import('vue-router')['RouterView']
//     Select: typeof import('primevue/select')['default']
//   }
// }
