"""URLs for the generated external API views.

This module was generated by the ``generate_graph_views`` management command.
Do not edit by hand; re-run the command instead.

Include it from the project's urls.py:

    urlpatterns = [
        ...
        path("", include("bcrhp.urls_api_generated")),
    ]

These routes are what the drf_spectacular OpenAPI generator introspects.
"""

from django.urls import path

from bcrhp.views.generated import (
    BcHeritageFunctionListView,
    BcHeritageFunctionView,
    BcHeritageResourcePlaceListView,
    BcHeritageResourcePlaceView,
    BcPropertyAddressListView,
    BcPropertyAddressView,
    BcPropertyLegalDescriptionListView,
    BcPropertyLegalDescriptionView,
    BcRightListView,
    BcRightView,
    HeritageSiteListView,
    HeritageSiteView,
    HeritageSiteHistoricalDataListView,
    HeritageSiteHistoricalDataView,
    LegislativeActListView,
    LegislativeActView,
    LgPersonListView,
    LgPersonView,
    LocalGovernmentListView,
    LocalGovernmentView,
    ProjectSandboxListView,
    ProjectSandboxView,
    SiteSubmissionListView,
    SiteSubmissionView,
)

urlpatterns = [
    path(
        "api/external/bc_heritage_function/",
        BcHeritageFunctionListView.as_view(),
        name="api_bc_heritage_function_list",
    ),
    path(
        "api/external/bc_heritage_function/<uuid:pk>/",
        BcHeritageFunctionView.as_view(),
        name="api_bc_heritage_function",
    ),
    path(
        "api/external/bc_heritage_resource_place/",
        BcHeritageResourcePlaceListView.as_view(),
        name="api_bc_heritage_resource_place_list",
    ),
    path(
        "api/external/bc_heritage_resource_place/<uuid:pk>/",
        BcHeritageResourcePlaceView.as_view(),
        name="api_bc_heritage_resource_place",
    ),
    path(
        "api/external/bc_property_address/",
        BcPropertyAddressListView.as_view(),
        name="api_bc_property_address_list",
    ),
    path(
        "api/external/bc_property_address/<uuid:pk>/",
        BcPropertyAddressView.as_view(),
        name="api_bc_property_address",
    ),
    path(
        "api/external/bc_property_legal_description/",
        BcPropertyLegalDescriptionListView.as_view(),
        name="api_bc_property_legal_description_list",
    ),
    path(
        "api/external/bc_property_legal_description/<uuid:pk>/",
        BcPropertyLegalDescriptionView.as_view(),
        name="api_bc_property_legal_description",
    ),
    path(
        "api/external/bc_right/",
        BcRightListView.as_view(),
        name="api_bc_right_list",
    ),
    path(
        "api/external/bc_right/<uuid:pk>/",
        BcRightView.as_view(),
        name="api_bc_right",
    ),
    path(
        "api/external/heritage_site/",
        HeritageSiteListView.as_view(),
        name="api_heritage_site_list",
    ),
    path(
        "api/external/heritage_site/<uuid:pk>/",
        HeritageSiteView.as_view(),
        name="api_heritage_site",
    ),
    path(
        "api/external/heritage_site_historical_data/",
        HeritageSiteHistoricalDataListView.as_view(),
        name="api_heritage_site_historical_data_list",
    ),
    path(
        "api/external/heritage_site_historical_data/<uuid:pk>/",
        HeritageSiteHistoricalDataView.as_view(),
        name="api_heritage_site_historical_data",
    ),
    path(
        "api/external/legislative_act/",
        LegislativeActListView.as_view(),
        name="api_legislative_act_list",
    ),
    path(
        "api/external/legislative_act/<uuid:pk>/",
        LegislativeActView.as_view(),
        name="api_legislative_act",
    ),
    path(
        "api/external/lg_person/",
        LgPersonListView.as_view(),
        name="api_lg_person_list",
    ),
    path(
        "api/external/lg_person/<uuid:pk>/",
        LgPersonView.as_view(),
        name="api_lg_person",
    ),
    path(
        "api/external/local_government/",
        LocalGovernmentListView.as_view(),
        name="api_local_government_list",
    ),
    path(
        "api/external/local_government/<uuid:pk>/",
        LocalGovernmentView.as_view(),
        name="api_local_government",
    ),
    path(
        "api/external/project_sandbox/",
        ProjectSandboxListView.as_view(),
        name="api_project_sandbox_list",
    ),
    path(
        "api/external/project_sandbox/<uuid:pk>/",
        ProjectSandboxView.as_view(),
        name="api_project_sandbox",
    ),
    path(
        "api/external/site_submission/",
        SiteSubmissionListView.as_view(),
        name="api_site_submission_list",
    ),
    path(
        "api/external/site_submission/<uuid:pk>/",
        SiteSubmissionView.as_view(),
        name="api_site_submission",
    ),
]
