"""URLs for the generated API views.

This module was generated by the ``generate_graph_views`` management command.
Do not edit by hand; re-run the command instead.

Include it from the project's urls.py:

    urlpatterns = [
        ...
        path("", include("bcrhp.urls_api_generated")),
    ]

These routes are what the drf_spectacular OpenAPI generator introspects.
"""

from django.urls import path

from bcrhp.views.generated import (
    HeritageSiteListView,
    HeritageSiteView,
    HeritageSiteHistoricalDataListView,
    HeritageSiteHistoricalDataView,
    LegislativeActListView,
    LegislativeActView,
    LgPersonListView,
    LgPersonView,
    LocalGovernmentListView,
    LocalGovernmentView,
    ProjectSandboxListView,
    ProjectSandboxView,
    SiteSubmissionListView,
    SiteSubmissionView,
)

urlpatterns = [
    path(
        "bcrhp/api/heritage_site/",
        HeritageSiteListView.as_view(),
        name="api_heritage_site_list",
    ),
    path(
        "bcrhp/api/heritage_site/<uuid:pk>/",
        HeritageSiteView.as_view(),
        name="api_heritage_site",
    ),
    path(
        "bcrhp/api/heritage_site_historical_data/",
        HeritageSiteHistoricalDataListView.as_view(),
        name="api_heritage_site_historical_data_list",
    ),
    path(
        "bcrhp/api/heritage_site_historical_data/<uuid:pk>/",
        HeritageSiteHistoricalDataView.as_view(),
        name="api_heritage_site_historical_data",
    ),
    path(
        "bcrhp/api/legislative_act/",
        LegislativeActListView.as_view(),
        name="api_legislative_act_list",
    ),
    path(
        "bcrhp/api/legislative_act/<uuid:pk>/",
        LegislativeActView.as_view(),
        name="api_legislative_act",
    ),
    path(
        "bcrhp/api/lg_person/",
        LgPersonListView.as_view(),
        name="api_lg_person_list",
    ),
    path(
        "bcrhp/api/lg_person/<uuid:pk>/",
        LgPersonView.as_view(),
        name="api_lg_person",
    ),
    path(
        "bcrhp/api/local_government/",
        LocalGovernmentListView.as_view(),
        name="api_local_government_list",
    ),
    path(
        "bcrhp/api/local_government/<uuid:pk>/",
        LocalGovernmentView.as_view(),
        name="api_local_government",
    ),
    path(
        "bcrhp/api/project_sandbox/",
        ProjectSandboxListView.as_view(),
        name="api_project_sandbox_list",
    ),
    path(
        "bcrhp/api/project_sandbox/<uuid:pk>/",
        ProjectSandboxView.as_view(),
        name="api_project_sandbox",
    ),
    path(
        "bcrhp/api/site_submission/",
        SiteSubmissionListView.as_view(),
        name="api_site_submission_list",
    ),
    path(
        "bcrhp/api/site_submission/<uuid:pk>/",
        SiteSubmissionView.as_view(),
        name="api_site_submission",
    ),
]
