# Generated by Django 4.2.1 on 2025-08-01 15:55

import os
import sys
import bcgov_arches_common.migrations.operations.privileged_sql
from bcrhp.migrations.util.migration_util import format_files_into_sql
from bcrhp.settings import DATABASES
from django.db import migrations

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# bcrhp.migrations.1203_reload_map_layers -
# bcrhp.migrations.1205_remove_undefined_widget_def - Not necessary
# bcrhp.migrations.1224_remove_duplicate_overlays - Maybe not necessary?
# bcrhp.migrations.636_update_search_card_descriptor - Not necessary
# bcrhp.migrations.910_update_heritage_usernames - Not necessary


def format_sql(file_path: str, params: dict = None) -> str:
    with open(os.path.join(os.path.dirname(__file__), "..", file_path)) as file:
        sql_string = file.read()
        return sql_string.format(**params) if params else sql_string


class Migration(migrations.Migration):

    replaces = [
        ("bcrhp", "636_update_search_card_descriptor"),
        ("bcrhp", "910_update_heritage_usernames"),
        ("bcrhp", "1034_fix_file_urls"),
        ("bcrhp", "1075_fix_null_sortorder"),
        ("bcrhp", "1108_fix_null_card_sortorder"),
        ("bcrhp", "1044_disable_download_email_notifications"),
        ("bcrhp", "1036_update_heritage_site_export_config"),
        ("bcrhp", "1111_add_missing_submission_documents_config"),
        ("bcrhp", "1168_fix_mv_chronology_index"),
        ("bcrhp", "1081_drop_materialized_views"),
        ("bcrhp", "1081_recreate_materialized_views"),
        ("bcrhp", "1081_add_missing_featureids"),
        ("bcrhp", "1205_remove_undefined_widget_def"),
        ("bcrhp", "1203_reload_map_layers"),
        ("bcrhp", "1203_update_site_boundary_legend"),
        ("bcrhp", "1224_remove_duplicate_overlays"),
    ]

    dependencies = [
        ("bcrhp", "0002_load_package"),
    ]

    db_databc_user = DATABASES["default"]["DATABC_USERNAME"]
    app_user = DATABASES["default"]["USER"]

    sql_dir = os.path.join(os.path.dirname(__file__), "sql", "2024")

    @staticmethod
    def run_operations(app, schema_editor):
        if "test" in sys.argv:
            return
        sql_dir = Migration.sql_dir
        db_databc_user = Migration.db_databc_user
        app_user = Migration.app_user
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_bcrhp_build_image_caption.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_02__bc_get_utm_zone.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_02__bc_get_utm_srid.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_02__bc_get_utm_easting.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_02__bc_get_utm_northing.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_get_uuid_lookup_table.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-08__get_map_attribute_data.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(
                ["2024-02-29_16__databc_html_to_plain_string.sql"], sql_dir
            )
        )
        schema_editor.execute(
            format_files_into_sql(
                ["2024-02-29_17__databc_authority_priority.sql"], sql_dir
            )
        )
        schema_editor.execute(
            format_files_into_sql(
                ["2024-02-29_15__databc_get_first_address.sql"], sql_dir
            )
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_heritage_function.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_site_record_admin.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_heritage_class.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_government.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(
                ["2024-11-29_mv_bc_statement_of_significance.sql"], sql_dir
            )
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_chronology.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_heritage_theme.sql"], sql_dir)
        )
        # schema_editor.execute(format_files_into_sql(["2024-12-05_fix_object_owner.sql"], sql_dir))
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_construction_actors.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_property_address.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_site_names.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_bc_right.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_01__mv_borden_number.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_08__mv_protection_event.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_05__mv_legal_description.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_bcrhp_crhp_data_vw.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_mv_site_protection_event.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(
                ["2024-11-29_mv_unique_property_address.sql"], sql_dir
            )
        )
        schema_editor.execute(
            format_files_into_sql(["2024-02-29_14__mv_site_boundary.sql"], sql_dir)
        )
        schema_editor.execute(
            format_files_into_sql(
                ["2024-11-29_refresh_materialized_views.sql"], sql_dir
            )
        )
        schema_editor.execute(
            format_files_into_sql(["2024-11-29_v_historic_site.sql"], sql_dir)
        )
        schema_editor.execute(
            format_sql(
                os.path.join(sql_dir, "2024-11-29_heritage_site.csv_export.sql"),
                {"app_user": app_user},
            )
        )
        schema_editor.execute(
            format_sql(
                os.path.join(sql_dir, "2024-11-29_v_historic_enviro_onerow_site.sql"),
                {"db_databc_user": db_databc_user},
            )
        )

    operations = [
        migrations.RunPython(run_operations, migrations.RunPython.noop),
    ]
