# Generated by Django 5.2.12 on 2026-04-01 03:10

from django.db import migrations
from arches.app.models.models import FunctionXGraph, Function, Graph


def forwards(apps, schema_editor):
    graph_functions = FunctionXGraph.objects.filter(
        function__classname__in=["AdminOnlyAccess", "RestrictedSiteAccess"]
    ).delete()


def backwards(apps, schema_editor):
    admin_function = Function.objects.get(classname="AdminOnlyAccess")
    for graph in Graph.objects.filter(
        slug__in=[
            "lg_person",
            "project_sandbox",
            "site_submission",
            "heritage_site_historical_data",
        ]
    ).all():
        FunctionXGraph.objects.create(function=admin_function, graph=graph)

    restricted_function = Function.objects.get(classname="RestrictedSiteAccess")
    heritage_site = Graph.objects.get(slug="heritage_site")
    FunctionXGraph.objects.create(function=restricted_function, graph=heritage_site)


class Migration(migrations.Migration):

    dependencies = [
        ("bcrhp", "0129_drop_1034_backup_tables"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
