arches_server_port: "8001"

db_databc_user: "proxy_databc_prod"

webpack_internal_url: "https://prodapps-early.nrs.bcgov:8000"

# This gets the password from the <instance>_password.yml file
hria_db:
  user: "proxy_bcrhp"
  password: "{{ hria_db_password }}"
  host: "nrkdb01.bcgov"
  service_name: "hriaprd1.nrs.bcgov"
  port: "1521"
  application_user: "{{ hria_application_user }}"

oauth_auth_endpoint: "https://loginproxy.gov.bc.ca/auth/realms/bcregistry/protocol/openid-connect/auth"
oauth_token_endpoint: "https://loginproxy.gov.bc.ca/auth/realms/bcregistry/protocol/openid-connect/token"
oauth_jwks_uri: "https://loginproxy.gov.bc.ca/auth/realms/bcregistry/protocol/openid-connect/certs"
oauth_server_metadata_url: "https://loginproxy.gov.bc.ca/auth/realms/bcregistry/.well-known/openid-configuration"

bcap_api_host: "https://prodapps-early.nrs.bcgov:8000"
